#!/usr/bin/env python3
"""Generate a LaTeX runtime comparison table from simulation log files."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, stdev
from typing import Sequence

from plot_state_simulation_times import load_times_from_log


@dataclass
class RuntimeStats:
    name: str
    times: list[float]
    avg: float
    std: float | None


@dataclass
class ComparisonRow:
    simulation: str
    matlab: RuntimeStats
    cpp: RuntimeStats
    speedup: float


LOG_CONFIG = [
    {
        "name": "State tracking (clean)",
        "cpp_log": "C++/cpp_output.log",
        "matlab_log": "matlab/cstr/clean/matlab_output.log",
    },
    {
        "name": "State tracking (attacked)",
        "cpp_log": "C++/cpp_attacked_output.log",
        "matlab_log": "matlab/cstr/attacked/matlab_output.log",
    },
]


def compute_stats(name: str, times: list[float]) -> RuntimeStats:
    avg = mean(times)
    s = stdev(times) if len(times) > 1 else None
    return RuntimeStats(name=name, times=times, avg=avg, std=s)


def build_comparison_rows(base_dir: Path) -> list[ComparisonRow]:
    rows: list[ComparisonRow] = []
    for cfg in LOG_CONFIG:
        cpp_times = load_times_from_log(base_dir / cfg["cpp_log"])
        matlab_times = load_times_from_log(base_dir / cfg["matlab_log"])
        cpp_stats = compute_stats("C++", cpp_times)
        matlab_stats = compute_stats("MATLAB", matlab_times)
        speedup = matlab_stats.avg / cpp_stats.avg if cpp_stats.avg > 0 else float("inf")
        rows.append(
            ComparisonRow(
                simulation=cfg["name"],
                matlab=matlab_stats,
                cpp=cpp_stats,
                speedup=speedup,
            )
        )
    return rows


def _fmt_time(stats: RuntimeStats) -> str:
    if stats.std is not None:
        return f"${stats.avg:.4f} \\pm {stats.std:.4f}$"
    return f"${stats.avg:.6f}$"


def render_latex_table(rows: list[ComparisonRow]) -> str:
    lines = [
        "% Auto-generated by generate_runtime_table.py -- do not edit manually.",
        "\\begin{table}[htbp]",
        "\t\\centering",
        "\t\\caption{Runtime comparison between MATLAB and C++ CSTR simulations",
        "\t\t($n = 45{,}000$ steps, $\\tau = 0.001$\\,s, 50 runs each).}",
        "\t\\label{tab:runtime-comparison}",
        "\t\\begin{tabular}{lccc}",
        "\t\t\\toprule",
        "\t\tSimulation & MATLAB (s) & C++ (s) & Speedup \\\\",
        "\t\t\\midrule",
    ]
    for row in rows:
        matlab_str = _fmt_time(row.matlab)
        cpp_str = _fmt_time(row.cpp)
        speedup_str = f"${row.speedup:.1f}\\times$"
        lines.append(f"\t\t{row.simulation} & {matlab_str} & {cpp_str} & {speedup_str} \\\\")
    lines.extend([
        "\t\t\\bottomrule",
        "\t\\end{tabular}",
        "\\end{table}",
    ])
    return "\n".join(lines) + "\n"


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a LaTeX runtime comparison table from simulation logs."
    )
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=None,
        help="Base directory containing C++ and matlab subdirectories with logs.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("runtime_comparison_table.tex"),
        help="Output .tex file path.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    base_dir = args.base_dir or Path(__file__).resolve().parent
    rows = build_comparison_rows(base_dir)
    table = render_latex_table(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")

    for row in rows:
        n_m = len(row.matlab.times)
        n_c = len(row.cpp.times)
        print(f"{row.simulation}:")
        print(f"  MATLAB: {row.matlab.avg:.6f}s avg ({n_m} samples)")
        print(f"  C++:    {row.cpp.avg:.6f}s avg ({n_c} samples)")
        print(f"  Speedup: {row.speedup:.1f}x")
    print(f"Saved: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
