[env]
DCMAKE_EXPORT_COMPILE_COMMANDS = "ON"

[tasks.debug]
run = [
  "cmake . -B ./build -DCMAKE_BUILD_TYPE=Debug",
  "make -C ./build",
  "./build/fig2a &",
  "./build/fig2b &",
  "./build/fig2c &",
  "./build/validate_output /Users/Apple/work/tracking-control-network/src/simulations/matlab/Fig2/fig2a_reference.csv /Users/Apple/work/tracking-control-network/src/simulations/C++/fig2a_cpp_output.csv",
]

[tasks.test]
run = [
  "cmake . -B ./build -DCMAKE_BUILD_TYPE=Release",
  "make -C ./build",
  "./build/fig2a &",
  "./build/fig2b &",
  "./build/fig2c &",
  "./build/validate_output /Users/Apple/work/tracking-control-network/src/simulations/matlab/Fig2/fig2a_reference.csv /Users/Apple/work/tracking-control-network/src/simulations/C++/fig2a_cpp_output.csv",
]

[tasks.attacked]

run = [
  "cmake . -B ./build -DCMAKE_BUILD_TYPE=Release",
  "make -C ./build",
  "./build/fig2a_attacked &",
]
